"""fase4: idempotencia, feedback, timestamps de processamento e ai_interactions

Revision ID: 1f949d3ab187
Revises: 31976b5aafde
Create Date: 2026-08-12 15:47:50.839842

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f949d3ab187'
down_revision: str | Sequence[str] | None = '31976b5aafde'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens_estimate', sa.Integer(), nullable=False),
    sa.Column('completion_tokens_estimate', sa.Integer(), nullable=False),
    sa.Column('cost_estimate_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_interactions_conversation_id'), 'ai_interactions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_interactions_owner_id'), 'ai_interactions', ['owner_id'], unique=False)
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('processing_finished_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('feedback', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback')
    op.drop_column('documents', 'processing_finished_at')
    op.drop_column('documents', 'processing_started_at')
    op.drop_index(op.f('ix_ai_interactions_owner_id'), table_name='ai_interactions')
    op.drop_index(op.f('ix_ai_interactions_conversation_id'), table_name='ai_interactions')
    op.drop_table('ai_interactions')
    # ### end Alembic commands ###
