"""add status column to documents

Revision ID: 31976b5aafde
Revises: d99984303723
Create Date: 2026-07-23 19:01:02.069320

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31976b5aafde'
down_revision: str | Sequence[str] | None = 'd99984303723'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'documents',
        sa.Column('status', sa.String(length=20), nullable=False, server_default='ready'),
    )
    op.alter_column('documents', 'status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
